**2. Density Operators**

**2.1. Pure states**

Coherent superposition, or pure states:

$$|\psi\rangle = c_1 |\phi_1\rangle + c_2|\phi_2\rangle + ... + c_d|\phi_d\rangle = \sum_{j=1}^{d}{c_j|\phi_j}\rangle$$

Expectation values:

$$\langle A \rangle = \langle\psi|A|\psi\rangle$$

In [23]:
import numpy as np

d = 3
basis = np.eye(d)
print(f'basis = \n{basis}\n')

# some coefficients of the state
cs = np.array([1/np.sqrt(3), 1j/np.sqrt(3), -1/np.sqrt(3)])
print(f'cs = {cs}\n')

# the state psi
psi = sum([c*b for c, b in zip(cs, basis)])
print(f'psi = {psi}\n')

# some operator
A = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]])
print(f'A = \n{A}\n')

# the expectation value of A in the state psi
exp_A = np.real(psi.conj().T @ A @ psi)
print(f'<A> = {exp_A}\n')

basis = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

cs = [ 0.57735027+0.j          0.        +0.57735027j -0.57735027+0.j        ]

psi = [ 0.57735027+0.j          0.        +0.57735027j -0.57735027+0.j        ]

A = 
[[1 0 0]
 [0 2 0]
 [0 0 3]]

<A> = 2.0000000000000004



**2.3. Definition and properties of the density operator**

The density operator:

$$\rho = \sum_{i,j=1}^{d}p_{ij}|\psi_i\rangle\langle\psi_j|$$

The expactation value can be calculated as,

$$\langle A \rangle = \text{Tr}[A\rho]$$

In [28]:
import numpy as np

d = 3
basis = np.eye(d)

# some probabilities
ps = np.array([0.1, 0.3, 0.6])

# the density operator of pure state
rho = sum([p*np.outer(b, b.conj()) for p, b in zip(ps, basis)])
print(f'rho = \n{rho}\n')

# some operator
A = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]])

# the expectation value of A in the state rho
exp_A = np.real(np.trace(rho @ A))
print(f'<A> = {exp_A}\n')

rho = 
[[0.1 0.  0. ]
 [0.  0.3 0. ]
 [0.  0.  0.6]]

<A> = 2.5



**2.4. Composite systems**

**2.4.1. Tensor product and partial trace**

The bipartite pure state:

$$|\psi(\theta)\rangle = \cos(\theta)|00\rangle + \sin(\theta)|11\rangle$$

In [35]:
# Kronecker product
psi1 = np.array([1, 0])
psi2 = np.array([0, 1])
psi = np.kron(psi1, psi2)
print(f'psi = {psi}\n')

# partial trace
d1 = 2
d2 = 2

rho = np.outer(psi, psi.conj())
print(f'rho = \n{rho}\n')

rho1 = np.trace(rho.reshape(d1, d2, d1, d2), axis1=1, axis2=3)
print(f'rho1 = \n{rho1}\n')

rho2 = np.trace(rho.reshape(d1, d2, d1, d2), axis1=0, axis2=2)
print(f'rho2 = \n{rho2}\n')

psi = [0 1 0 0]

rho = 
[[0 0 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 0 0 0]]

rho1 = 
[[1 0]
 [0 0]]

rho2 = 
[[0 0]
 [0 1]]

